### ISSUE TITLE
The node was expected to be an ArrayNode. This Configuration includes an edge case not supported yet.

### ISSUE THREAD

**Issue by carly-cloud** [aws/aws-sdk-php-symfony#108]
Might be related to [https://github.com/aws/aws-sdk-php-symfony/issues/88](https://github.com/aws/aws-sdk-php-symfony/issues/88)

### Describe the bug

I am getting this warning for my AWS Symfony configuration:

```
app.WARNING: Failed to generate ConfigBuilder for extension Aws\Symfony\DependencyInjection\AwsExtension: The node was expected to be an ArrayNode. This Configuration includes an edge case not supported yet. {"exception":"[object] (LogicException(code: 0): The node was expected to be an ArrayNode. This Configuration includes an edge case not supported yet. at /www/vendor/symfony/config/Builder/ConfigBuilderGenerator.php:108)","extensionClass":"Aws\\Symfony\\DependencyInjection\\AwsExtension"} []
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

not showing a warning

### Current Behavior

showing warning message

### Reproduction Steps

**aws.yaml**
```
when@prod:
  aws:
    version: latest
    region: eu-central-1
    credentials: ~
    DynamoDb:
      region: us-east-1

when@dev:
  aws:
    version: latest
    region: eu-central-1
    profile: staging
    DynamoDb:
      region: us-east-1
```

### SDK version used

aws/aws-sdk-php-symfony: 2.7
aws/aws-sdk-php 3.336

### Environment details (OS name and version, etc.)

PHP 8.3.10
Amazon Linux 2023

**Comment by bodendorfer-simplethings** [comment]
Same behaviour with 
aws/aws-sdk-php                     3.343.6
aws/aws-sdk-php-symfony      2.8.0

aws.yaml
```
aws:
    version: latest
    region: de
    endpoint: "%env(AWS_ENDPOINT_URL)%"
    credentials:
        key: "%env(AWS_ACCESS_KEY_ID)%"
        secret: "%env(AWS_SECRET_ACCESS_KEY)%"
```
