### ISSUE TITLE
How to pass parameters in SesClient

### ISSUE THREAD

**Issue by stavros-liaskos** [aws/aws-sdk-php-symfony#21]
I have a difficulty passing the parameters to SesClient. At least that's what I believe given the error message. I tried countless configurations but I will forward only the one that seems correct to me.
`composer show --installed`:
```
aws/aws-sdk-php                          3.19.24 AWS SDK for PHP - Use Amazon Web Services in your PHP project
aws/aws-sdk-php-symfony                  1.2.0   A Symfony bundle for v3 of the AWS SDK for PHP
--- more ---
```

In my `config.yml` I have : 
```yml
aws:
    key: myKey
    secret: topSecret
    region: eu-west-1
    version: latest
```

In my `services.yml`I have:
```yaml
services:
  aws.ses:
    class:  Aws\Ses\SesClient
    arguments:
        - [key, secret, region, version]
```
In my `src/AppBundle/Controller/AwsController.php` :
```php
class AwsController extends Controller
{
    /**
     * @Route("/aws", name="aws")
     */
    public function awsAction()
    {
        $mailer = $this->get('aws.ses');
        return new Response ("");
    }
}
```

But I get this error: 
```
Missing required client configuration options: 

region: (string)

A "region" configuration value is required for the "email" service
(e.g., "us-west-2"). A list of available public regions and endpoints can be
found at http://docs.aws.amazon.com/general/latest/gr/rande.html.

version: (string)

A "version" configuration value is required. Specifying a version constraint
ensures that your code will not be affected by a breaking change made to the
service. For example, when using Amazon S3, you can lock your API version to
"2006-03-01".

Your build of the SDK has the following version(s) of "email": * "2010-12-01"

You may provide "latest" to the "version" configuration value to utilize the
most recent available API version that your client's API provider can find.
Note: Using 'latest' in a production application is not recommended.

A list of available API versions can be found on each client's API documentation
page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are
unable to load a specific API version, then you may need to update your copy of
the SDK.
```

Any ideas on what am I missing?

**Comment by cjyclaire** [comment]
@stavros-liaskos In your `config.yaml` file, could you try add something like
``` php
     Ses:
        region: 'us-west-2'
        version: '2010-12-01'
```

**Comment by stavros-liaskos** [comment]
@cjyclaire I tried that and now I get the error:
```
There is no extension able to load the configuration for "aws.ses" (in 
projectPath/app/config/config_dev.yml). Looked for namespace "aws.ses", found "framework", 
"security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "aws", "debug", 
"web_profiler", "sensio_distribution"
```
But I have already added the following configuration in every config file just to be sure(app/config/config.yml, src/AppBundle/Resources/config/config.yml, app/config/config_dev.yml) :   
```

aws.Ses:
    key: myKey
    secret: topSecret
    region: eu-west-1
    version: latest
aws.ses:
    key: myKey
    secret: topSecret
    region: eu-west-1
    version: latest
Ses:
    key: myKey
    secret: topSecret
    region: eu-west-1
    version: latest
ses:
    key: myKey
    secret: topSecret
    region: eu-west-1
    version: latest
```

**Comment by cjyclaire** [comment]
@stavros-liaskos The error message might be indicating some indenting issue.
Could you double check that they formatted correctly like the example [here](https://github.com/aws/aws-sdk-php-symfony#sample-yml-configuration).

**Comment by stavros-liaskos** [comment]
@cjyclaire Since I don't use DynamoDb, S3, Sqs, CloudSearchDomain and I don't use the Credentials object, all that's left from the example configuration (adding also the keys) is:
```
aws:
    key: myKey
    secret: topSecret
    region: eu-west-1
    version: latest
```

Also I don't use the services in the config.yml example.

What about my `services.yml`? Are the arguments configured correctly?

**Comment by cjyclaire** [comment]
@stavros-liaskos It's definitely no problem if you don't use S3 etc., I'm actually suggesting the entire indentation format there, so for your case, your `config.yml` file should look like:
``` php
aws:
    key: myKey
    secret: topSecret
    region: eu-west-1
    version: latest
    Ses:
        key: myKey
        secret: topSecret
        region: eu-west-1
        version: latest
```

**Comment by stavros-liaskos** [comment]
I finally implemented another way to pass the parameters and it looks to me like a best practice at least according to Symfony (given that secret ids are used).
in my `parameters.yml.dist`:
```yml
parameters:
# more..
    ses_key_id: myKey
    ses_secret: topSecret
    region: eu-west-1
    version: latest
```
then in the `services.xml`:
```xml
<!-- more -->
<service id="my_mail.swiftmailer.transport.ses" class="path\to\the\Class">
    <argument type="service" id="swiftmailer.mailer.default.transport.eventdispatcher" />
    <argument>%ses_key_id%</argument>
    <argument>%ses_secret%</argument>
    <argument>%region%</argument>
    <argument>%version%</argument>
</service>
```
Then I use the service
