### ISSUE TITLE
Custom S3 Client service throwing error

### ISSUE THREAD

**Issue by MatthewBooth** [aws/aws-sdk-php-symfony#35]
I'm attempting to create two S3 client services for my application. Each has different permissions as per the IAM roles the keys have.

I'm getting this error:

`Type error: Argument 1 passed to Aws\\S3\\S3Client::__construct() must be of the type array, string given`

This is the services.yml entry:

```
app.aws.read:
        class: '%aws.s3.class%'
        arguments: ['%aws_keys_read_key%', '%aws_keys_read_secret%']
```
I don't see why this shouldn't work since an array is being given as the argument.

**Comment by MatthewBooth** [comment]
Ok, so it looks like it's done like this:

```yaml
app.s3.read:
        class: '%aws.s3.class%'
        arguments:
            -
                version: latest # or 'latest'
                region: "eu-west-2" # 'eu-central-1' for example
                credentials:
                    key: '%aws_keys_read_key%'
                    secret: '%aws_keys_read_secret%'
```
