### ISSUE TITLE
Setting region in configuration doesn't work

### ISSUE THREAD

**Issue by Rewieer** [aws/aws-sdk-php-symfony#37]
I tried the following
```yaml
aws:
    version: latest
    region: eu-west-2
    credentials:
        key: "%aws_s3_credentials_key%"
        secret: "%aws_s3_credentials_secret%"
    s3:
        region: eu-west-2
    glacier:
        region: eu-west-1
```

But the region for my glacier service still is eu-west-2 :(
