### ISSUE TITLE
Handle merging of multiple configuration files

### ISSUE THREAD

**Issue by glynnforrest** [aws/aws-sdk-php-symfony#51]
If I have two files in a typical flex application, `config/packages/aws.yaml` and `config/packages/dev/aws.yaml`, I'd expect anything in `dev/aws.yaml` to be merged into `aws.yaml`. Instead it completely replaces it:

### aws.yaml
```
aws:
    region: eu-west-1
    credentials: ~
    version: latest
    retries: 5
```

### dev/aws.yaml
```
aws:
    retries: 10
```

## Expected
`./bin/console debug:config aws --env=dev`
```
aws:
    region: eu-west-1
    credentials: ~
    version: latest
    retries: 10
```

## Actual
`./bin/console debug:config aws --env=dev`
```
aws:
    retries: 10
```

Because `aws` node is a `variable` node (see [here](https://github.com/aws/aws-sdk-php-symfony/blob/master/src/DependencyInjection/Configuration.php#L14)), the configs aren't merged as normally expected with bundles, but completely replaced.

Either we should come up with a way to merge the configurations, or perhaps just document the behaviour somewhere?

```
composer show | grep aws
aws/aws-sdk-php                       3.69.9 
aws/aws-sdk-php-symfony              v2.0.0
```

Thank you.
