### ISSUE TITLE
Cache client credentials

### ISSUE THREAD

**Issue by cjunge-work** [aws/aws-sdk-php-symfony#62]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
aws/aws-sdk-php 3.133.26

### Version of AWS Service Provider for Symfony?
aws/aws-sdk-php-symfony 1.3.0

### Version of Symfony (`bin/console --version` in project dir)?
Symfony 3.4.38

### Version of PHP (`php -v`)?
PHP 7.3.13

### What issue did you see?
Unable to configure the cache for the client credentials

### Steps to reproduce
N/A

### Additional context
I'm trying to configure caching the client credentials using the DoctrineCacheAdaptor, but I am unable to get the cache to be used. All requests are still accessing the credentials each time the command is run.

(We swap credential providers on production, thus why we have 2 different configurations, but neither are using the cache.)

```
// config.yml
aws:
    version: latest
    region: ap-southeast-2
    credentials: "@aws_credentials"
    sqs:
        credentials: "@aws_cache_credentials"
```
```
//services.yml
    aws_cache_credentials:
        class: Aws\DoctrineCacheAdapter
        lazy:  true
        arguments:
            - "@doctrine_cache.providers.apcu"

    aws_credentials: aws_token_credentials
    aws_token_credentials:
        class: Aws\Credentials\Credentials
        lazy:  true
        arguments:
            - "%aws_credentials_key%"
            - "%aws_credentials_secret%"
    aws_instance_profile_credentials:
        class: Aws\Credentials\InstanceProfileProvider
        lazy:  true
```

The SQS Client is only using the default credentials, not the cache provider.
