### ISSUE TITLE
configure guzzle logger

### ISSUE THREAD

**Issue by Nemo64** [aws/aws-sdk-php-symfony#69]
### Is this related to a problem?
If you use this bundle, nothing will be logged.

### Feature description
I'd like the to configure guzzles logger by default.

### Describe alternatives you've considered
You can configure it but it isn't too obvious:
```yaml
aws:
    version: latest
    region: '%env(AWS_REGION)%'
    http:
        handler: '@aws.http_handler'

services:
    aws.http_handler:
        class: GuzzleHttp\HandlerStack
        factory: [GuzzleHttp\HandlerStack, create]
        calls:
            - [push, ['@aws.http_logger']]
    
    aws.http_logger:
        class: Closure
        factory: [GuzzleHttp\Middleware, log]
        arguments:
            - '@logger'
            - '@aws.log_formatter'
        tags:
            - {name: monolog.logger, channel: aws}

    aws.log_formatter:
        class: GuzzleHttp\MessageFormatter
        arguments:
            - '{method} {uri} HTTP/{version} {code}'
```
This configuration doesn't validate though as the `handler` option isn't defined here.

You can also the [8p/EightPointsGuzzleBundle](https://github.com/8p/EightPointsGuzzleBundle) and configure the `http_handler` option (don't confuse it with the `http.handler` option from above) to pass a preconfigured Guzzle instance.
